#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri May 24 16:58:29 PKT 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 6a1bb2eb2b934d02bd3419952288b995 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot T_AXI4_MASTER_behav xil_defaultlib.T_AXI4_MASTER -log elaborate.log"
xelab -wto 6a1bb2eb2b934d02bd3419952288b995 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot T_AXI4_MASTER_behav xil_defaultlib.T_AXI4_MASTER -log elaborate.log

