#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri May 24 19:00:42 PKT 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto b5d969fc6b7547a9a4e0d87f9c57878f --incr --debug typical --relax --mt 8 -L xil_defaultlib -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_5 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot T_AXI4_BLOCK_behav xil_defaultlib.T_AXI4_BLOCK xil_defaultlib.glbl -log elaborate.log"
xelab -wto b5d969fc6b7547a9a4e0d87f9c57878f --incr --debug typical --relax --mt 8 -L xil_defaultlib -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_5 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot T_AXI4_BLOCK_behav xil_defaultlib.T_AXI4_BLOCK xil_defaultlib.glbl -log elaborate.log

